name: AV Latency.com Toolkit - MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  HDMI-LATENCY_SOLUTION_FILE_PATH: "HDMI-Latency/HDMI-Latency.vcxproj"
  SPDIF-LATENCY_SOLUTION_FILE_PATH: "SPDIF-Latency/SPDIF-Latency.vcxproj"
  HDMI-TO-DIGITAL-AUDIO-LATENCY_SOLUTION_FILE_PATH: "HDMI-to-Digital-Audio-Latency/HDMI-to-Digital-Audio-Latency.vcxproj"
  AUDIO-DRIVER-CHECK_SOLUTION_FILE_PATH: "Audio-Driver-Check/Audio-Driver-Check.vcxproj"

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

#    - name: Restore NuGet packages
#      working-directory: ${{env.GITHUB_WORKSPACE}}
#      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build HDMI-Latency
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.HDMI-LATENCY_SOLUTION_FILE_PATH}}

    - name: Build SPDIF-Latency
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SPDIF-LATENCY_SOLUTION_FILE_PATH}}

    - name: HDMI-to-Digital-Audio-Latency
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.HDMI-TO-DIGITAL-AUDIO-LATENCY_SOLUTION_FILE_PATH}}

    - name: Build Audio-Driver-Check
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.AUDIO-DRIVER-CHECK_SOLUTION_FILE_PATH}}

    - name: Copying executables
      run: |
        New-Item "FinalFiles" -Type Directory
        New-Item "FinalFiles/AV Latency.com Toolkit" -Type Directory
        Copy-Item "HDMI-Latency/Release/HDMI-Latency/HDMI Audio Latency.exe" -Destination "FinalFiles/AV Latency.com Toolkit/HDMI Audio Latency.exe"
        Copy-Item "SPDIF-Latency/Release/SPDIF-Latency/SPDIF Latency.exe" -Destination "FinalFiles/AV Latency.com Toolkit/SPDIF Latency.exe"
        Copy-Item "HDMI-to-Digital-Audio-Latency/Release/HDMI-to-Digital-Audio-Latency/HDMI to ARC, eARC, or SPDIF Latency.exe" -Destination "FinalFiles/AV Latency.com Toolkit/HDMI to ARC, eARC, or SPDIF Latency.exe"
        Copy-Item "Audio-Driver-Check/Release/Audio-Generator-Driver-Check/Audio Generator Driver Check.exe" -Destination "FinalFiles/AV Latency.com Toolkit/Audio Generator Driver Check.exe"
      shell: powershell
    
    - name: Creating non tag artifact
      uses: actions/upload-artifact@v2
      if: ${{ !startsWith(github.ref, 'refs/tags/AVLatency.com-Toolkit-v') }}
      with:
        name: AVLatency.com-Toolkit
        path: "FinalFiles"
    
    - name: Creating tag artifact
      uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/AVLatency.com-Toolkit-v')
      with:
        name: ${{github.ref_name}}
        path: "FinalFiles"
